# Generated by Django 3.1.4 on 2020-12-23 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_cart_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tax',
        ),
    ]
