# Generated by Django 3.1.4 on 2020-12-16 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_category_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='categoryname',
        ),
    ]
